# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.countLineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.countLineEdit_2.setGeometry(QtCore.QRect(230, 60, 141, 31))
        self.countLineEdit_2.setObjectName("countLineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 235, 43))
        self.label.setObjectName("label")
        self.graphResultPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.graphResultPushButton.setGeometry(QtCore.QRect(380, 60, 251, 35))
        self.graphResultPushButton.setObjectName("graphResultPushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 232, 43))
        self.label_2.setObjectName("label_2")
        self.countLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.countLineEdit.setGeometry(QtCore.QRect(230, 20, 141, 31))
        self.countLineEdit.setObjectName("countLineEdit")
        self.kmeansPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.kmeansPushButton.setGeometry(QtCore.QRect(380, 100, 251, 34))
        self.kmeansPushButton.setObjectName("kmeansPushButton")
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setGeometry(QtCore.QRect(380, 20, 251, 34))
        self.startPushButton.setObjectName("startPushButton")
        self.resultTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.resultTableWidget.setGeometry(QtCore.QRect(10, 140, 621, 301))
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setColumnCount(3)
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)\

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Количество элементов из БД"))
        self.graphResultPushButton.setText(_translate("MainWindow", "Вывести графический результат"))
        self.label_2.setText(_translate("MainWindow", "Введите 8-ми значное число"))
        self.kmeansPushButton.setText(_translate("MainWindow", "Разбиение на 4 кластера"))
        self.startPushButton.setText(_translate("MainWindow", "Запустить анализ"))
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дополнительное число"))
        item = self.resultTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Число из списка"))
        item = self.resultTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Результат анализа"))

    def startAnalyse(self):
        print('it works')
